name: matseco_sample
description: Showcases the use of Material Segmented Control widget
version: 1.0.0
homepage: https://github.com/beagle-barks/material_segmented_control
publish_to: none

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_segmented_control:
    path: '..'

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
